message:
    cong: '"hello"'
server:
    port: 8082


spring:
    profiles:
        active: prod

---

spring:
    profiles: prod
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: malaydewangan1811
        url: jdbc:mysql://localhost:3306/dcbapp-prod
        username: root
    jpa:
        hibernate:
            ddl-auto: update
---
            spring:
                profiles: dev
                datasource:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    password: malaydewangan1811
                    url: jdbc:mysql://localhost:3306/dcbapp-dev
                    username: root
                jpa:
                    hibernate:
                        ddl-auto: update
